global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Configuração para scraping do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Configuração para scraping da aplicação NestJS
  - job_name: 'brainag-backend'
    static_configs:
      - targets: ['app:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  # Configuração para scraping do PostgreSQL (se habilitado postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 10s

  # Configuração para scraping do Redis (se habilitado redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 10s

  # Configuração para métricas do Node.js
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 5s

# Configuração de alertas (opcional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093